wrap up the scripts with a helper

diff --git a/gitit b/gitit
--- a/gitit
+++ b/gitit
@@ -2,14 +2,17 @@
 
 set -euo pipefail
 
-t=/tmp/foo
-rm -rf /tmp/foo
-mkdir /tmp/foo
-#t="$(mktemp -d)"
+#t=/tmp/foo
+#rm -rf /tmp/foo
+#mkdir /tmp/foo
+t="$(mktemp -d)"
 
 export GIT_DIR="$t/.git"
 export GIT_WORK_TREE="$t"
 git init --quiet
+
+echo export GIT_DIR="$t/.git"
+echo export GIT_WORK_TREE="$t"
 
 input_manifest="$1"
 shift
@@ -18,16 +21,16 @@ output_manifest="$t/$manifest_filename"
 
 bosh interpolate "$input_manifest" >"$output_manifest"
 
-git add -- "$manifest_filename"
-git commit -m "$manifest_filename"
+git add -- "$manifest_filename" >/dev/null
+git commit -m "$manifest_filename" >/dev/null
 
 ops_args=""
 
 for ops_file; do
   ops_args+=" -o $ops_file"
-  bosh interpolate "$input_manifest" $ops_args >"$output_manifest"
-  git commit -m "$(basename ${ops_file})" -- "$output_manifest"
+  bosh interpolate "$input_manifest" $ops_args >"$output_manifest" \
+  || { echo "Failed to apply ops file '$ops_file'; bailing out ..." >&2; false; }
+  git commit -m "$(basename ${ops_file} .yml | cut -c1-${MAXWIDTH:-999})" -- "$output_manifest" >/dev/null \
+  || true
 done 
 
-echo export GIT_DIR="$t/.git"
-echo export GIT_WORK_TREE="$t"
